Layout
BQuinteros/WeatherApp pull request #14
Opened 2020-04-21 14:17 UTC by BQuinteros

Added a basic layout to show the information about the weather of a city.
![image](https://user-images.githubusercontent.com/56684696/79876661-b497de80-83c1-11ea-82dc-5f320fddd59e.png)

2020-04-21 14:23 UTC, SartiMau requested changes

2020-04-21 14:23 UTC, SartiMau commented on WheaterApp/app/src/main/res/values/styles.xml
> +        <item name="android:layout_marginTop">124dp</item>
no hardcode, use dimens

2020-04-21 14:46 UTC, SartiMau submitted a review, later dismissed

2020-04-21 14:46 UTC, mauroLonghi commented on WheaterApp/app/src/main/res/layout/activity_details_city.xml
> +        android:textAlignment="center"
if you use in all the label's a style, in this case why did not use it?

2020-04-21 19:16 UTC, BQuinteros commented on WheaterApp/app/src/main/res/layout/activity_details_city.xml
> +        android:textAlignment="center"
done!

2020-04-21 19:16 UTC, BQuinteros commented
![image](https://user-images.githubusercontent.com/56684696/79904659-68619400-83eb-11ea-9199-05e3c4daa19f.png)

2020-04-21 19:54 UTC, nicolbidone approved these changes

2020-04-22 12:33 UTC, lucianoeli approved these changes

2020-04-22 12:34 UTC, mauroLonghi approved these changes

2020-04-22 12:35 UTC, merged