Braian.quinteros/motionlayout
BQuinteros/WeatherApp pull request #16
Opened 2020-04-23 16:44 UTC by BQuinteros

Changed the principal UI to a better solution using a motion layout.
![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/56684696/80125677-5e18d480-8568-11ea-90e9-d056f1109da4.gif)

2020-04-23 17:03 UTC, SartiMau approved these changes

2020-04-23 17:40 UTC, lucianoeli approved these changes

2020-04-24 13:03 UTC, BQuinteros commented
how it is working the app: 
![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/56684696/80215294-9543c000-8612-11ea-9540-9d55e74553b8.gif)
How it looks the image view on XML start: 
![image](https://user-images.githubusercontent.com/56684696/80215400-c58b5e80-8612-11ea-98ad-9aab0e63bc21.png)
How it looks the image view on XML end: 
![image](https://user-images.githubusercontent.com/56684696/80215445-d50aa780-8612-11ea-9a67-4ca4fcbb4aa6.png)

2020-04-24 13:08 UTC, SartiMau reviewed
can you add some styles in the layouts instead of all the properties?

2020-04-24 13:37 UTC, mauroLonghi approved these changes

2020-04-24 13:41 UTC, SartiMau requested changes

2020-04-24 13:41 UTC, SartiMau commented on WheaterApp/app/src/main/res/layout/activity_city.xml
> +    <TextView
background and padding can be in the style, put it there pls

2020-04-24 13:41 UTC, SartiMau commented on WheaterApp/app/src/main/res/layout/activity_city_motion_scene_end.xml
> +        android:layout_marginTop="@dimen/margin_top_city_activity_one_hundred_dp"
this can be inside the style

2020-04-24 14:07 UTC, BQuinteros commented on WheaterApp/app/src/main/res/layout/activity_city.xml
> +    <TextView
Done

2020-04-24 14:08 UTC, BQuinteros commented on WheaterApp/app/src/main/res/layout/activity_city_motion_scene_end.xml
> +        android:layout_marginTop="@dimen/margin_top_city_activity_one_hundred_dp"
Done

2020-04-24 14:17 UTC, nicolbidone approved these changes

2020-04-24 15:15 UTC, mauroLonghi approved these changes

2020-04-24 16:03 UTC, SartiMau approved these changes

2020-04-24 16:03 UTC, merged