Braian.quinteros/mainlayout
BQuinteros/WeatherApp pull request #2
Opened 2020-04-06 12:24 UTC by BQuinteros

In this pull request, you can see the main layout of the application where the user can put the name of the city. When you click done button change us to the other screen which is empty.

Evidence of how is the screen: 
![MainScreen](https://user-images.githubusercontent.com/56684696/78557840-eb79cc00-77e7-11ea-9a60-d42e88b72bb3.png)

2020-04-06 13:10 UTC, SartiMau requested changes

2020-04-06 13:10 UTC, SartiMau commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +        buttonDone.setOnClickListener {
add a response type in the livedata to do this logic.
the nextActivityIntent must be called from the updateUI method

2020-04-06 13:10 UTC, SartiMau commented on WheaterApp/app/src/main/java/com/example/weatherapp/viewmodels/CityMainViewModel.kt
> +        //TODO changed live data state
here is where you must set the state to nextActivity

2020-04-06 13:10 UTC, SartiMau commented on WheaterApp/buildsystem/dependencies.gradle
> +ext {
👏

2020-04-06 13:10 UTC, SartiMau commented on WheaterApp/domain/build.gradle
> +    implementation "org.koin:koin-androidx-viewmodel:2.0.0-GA"
use the dependencies that you create for this too 😄

2020-04-06 13:12 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +        buttonDone.setOnClickListener {
Yes, in the next Pull Request you can see the method called in the livedata logic.

2020-04-06 13:13 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/viewmodels/CityMainViewModel.kt
> +        //TODO changed live data state
Yes, in the next Pull Request you can see the method called in the livedata logic.

2020-04-06 13:17 UTC, BQuinteros commented on WheaterApp/buildsystem/dependencies.gradle
> +ext {
Thanks !

2020-04-06 13:18 UTC, BQuinteros commented on WheaterApp/domain/build.gradle
> +    implementation "org.koin:koin-androidx-viewmodel:2.0.0-GA"
Done

2020-04-06 13:43 UTC, mauroLonghi commented on WheaterApp/app/src/main/java/com/example/weatherapp/viewmodels/CityMainViewModel.kt
> +class CityMainViewModel: ViewModel() {
maybe you can use a contract to the ViewModel .

2020-04-06 13:44 UTC, mauroLonghi commented on WheaterApp/app/src/main/res/layout/activity_details_city.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
why you have a constraint inside another constraint?

2020-04-06 13:45 UTC, mauroLonghi commented on WheaterApp/buildsystem/dependencies.gradle
> +ext {
beautiful!

2020-04-06 13:46 UTC, nicolbidone commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +        val intent = Intent(this, DetailsCityActivity::class.java)
instead of this, you can use:
 public static Intent getIntent(Context context) {
        Intent intent = new Intent(context, MainActivity.class);
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_NEW_TASK);
        return intent;
    }
so the activity itself can return the intent

2020-04-06 13:46 UTC, nicolbidone commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +        startActivity(intent)
and replace the activity intent with
startActivity(new Intent(LoginActivity.getIntent(this)));

2020-04-06 13:55 UTC, nicolbidone commented on WheaterApp/app/src/main/res/layout/activity_city.xml
> +        app:layout_constraintStart_toStartOf="parent"
if you use android:layout_width="match_parent" you can ommit layout_constraintEnd_toEndOf and layout_constraintStart_toStartOf

2020-04-06 14:41 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/viewmodels/CityMainViewModel.kt
> +class CityMainViewModel: ViewModel() {
Done.

2020-04-06 14:45 UTC, BQuinteros commented on WheaterApp/app/src/main/res/layout/activity_details_city.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
It is the default constraint when we create a layout. If you want I change it later

2020-04-06 14:46 UTC, BQuinteros commented on WheaterApp/app/src/main/res/layout/activity_city.xml
> +        app:layout_constraintStart_toStartOf="parent"
Yep, It is true. Done it

2020-04-06 14:53 UTC, mauroLonghi commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +class CityMainActivity : AppCompatActivity() {
Sorry I not said this issue, here you can add a contract as "View" with the methods that implements...because this class is the "View" of the ViewModel..

2020-04-06 14:55 UTC, mauroLonghi commented on WheaterApp/app/src/main/res/layout/activity_details_city.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
ok, but it´s really necessary?

2020-04-06 14:55 UTC, nicolbidone commented on WheaterApp/app/src/main/res/values/strings.xml
> +    <string name="button_main_done">Done</string>
please use this naming convention
https://jeroenmols.com/blog/2016/03/07/resourcenaming/

2020-04-06 14:55 UTC, nicolbidone commented on WheaterApp/domain/src/main/java/com/example/domain/entities/City.kt
> +class City(
This can be a data class

2020-04-06 14:55 UTC, nicolbidone commented on WheaterApp/domain/src/main/java/com/example/domain/entities/City.kt
> +const val DEFAULT_TEMP = 0.0
Do you use these constants anywhere else? if not please move them to a companion object

2020-04-06 15:10 UTC, BQuinteros commented on WheaterApp/app/src/main/res/layout/activity_details_city.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
Yes, It is necessary because is the close of the constraint

2020-04-06 15:11 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +class CityMainActivity : AppCompatActivity() {
Done it

2020-04-06 15:22 UTC, BQuinteros commented on WheaterApp/domain/src/main/java/com/example/domain/entities/City.kt
> +class City(
Done

2020-04-06 15:22 UTC, BQuinteros commented on WheaterApp/domain/src/main/java/com/example/domain/entities/City.kt
> +const val DEFAULT_TEMP = 0.0
Done

2020-04-06 15:29 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +        val intent = Intent(this, DetailsCityActivity::class.java)
I found a better solution for this. I use an Extention function to the activity class, I use a generic function to said the intent which activity needs to be created.

2020-04-06 15:29 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +        startActivity(intent)
Same here

2020-04-06 16:02 UTC, BQuinteros commented on WheaterApp/app/src/main/res/values/strings.xml
> +    <string name="button_main_done">Done</string>
Done, so useful

2020-04-07 14:46 UTC, BQuinteros commented
Now we added a autocomplete in the text view and solved the comments we had. 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/56684696/78683224-68c73e80-78c5-11ea-8c0b-7c8e894a3b2e.gif)

2020-04-07 15:01 UTC, mauroLonghi commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +    private val viewModel: CityMainViewModel = CityMainViewModel()
Pls , instantiate the viewModel as : private val viewModel by _viewModel_<ClassViewModel>()

2020-04-07 15:03 UTC, SartiMau requested changes

2020-04-07 15:03 UTC, SartiMau commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +        getCityList()
I think that you should call the ViewModel to do this.. in this way the ViewModel will grant the initial state, and in the updateUI method you will call the getCityList

2020-04-07 15:06 UTC, nicolbidone commented on WheaterApp/app/src/main/res/layout/activity_city.xml
> +        app:layout_constraintStart_toStartOf="parent" />
if you use         
        android:layout_width="match_parent"
you can omit 
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"

2020-04-07 15:12 UTC, nicolbidone commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +        val intent = Intent(this, DetailsCityActivity::class.java)
Great solution!

2020-04-07 15:12 UTC, BQuinteros commented on WheaterApp/app/src/main/res/layout/activity_city.xml
> +        app:layout_constraintStart_toStartOf="parent" />
Done, I didn't check Its the second time you said to me sorry

2020-04-07 17:57 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +    private val viewModel: CityMainViewModel = CityMainViewModel()
Done!

2020-04-07 17:58 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +        getCityList()
Okey, I deleted that line and add one state in my status enum in the next PR I try to use that idea

2020-04-07 18:13 UTC, mauroLonghi approved these changes

2020-04-07 18:31 UTC, nicolbidone approved these changes

2020-04-07 18:49 UTC, SartiMau approved these changes

2020-04-07 18:49 UTC, merged