live data and update UI structure
BQuinteros/WeatherApp pull request #3
Opened 2020-04-07 20:39 UTC by BQuinteros

In this Pull Request, We put the basic structure of the updateUI of the main activity and the structure we are going to have in the ViewModel.
On the next Pull Request, we are going to do the call to the API and use coroutines
![LOADING](https://user-images.githubusercontent.com/56684696/78717152-8cef4380-78f6-11ea-8dc5-ae3989906bed.gif)

2020-04-08 12:11 UTC, SartiMau commented on WheaterApp/app/src/main/java/com/example/weatherapp/viewmodels/CityMainViewModel.kt
> +        mutableMainState.postValue(Event(Data(status = LOADING)))
This is incomplete I think.. the button only show de loader?

2020-04-08 12:21 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/viewmodels/CityMainViewModel.kt
> +        mutableMainState.postValue(Event(Data(status = LOADING)))
Yes is incomplete, in this Pull Request I only did the structure of how it look. In the next PR I going to do the call to the API and use a coroutine to do sync call

2020-04-08 12:26 UTC, mauroLonghi commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +                getCityList()
I think that it is not the best approach to show the list of cities, because:
1) when you start to write not show the list, instead showed when you stop writing
2) always shows the complete list, and it is wrong.

I think you can test another way to this funcionality

2020-04-09 14:55 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +                getCityList()
Done

2020-04-09 14:56 UTC, BQuinteros commented
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/56684696/78908673-cd66d280-7a58-11ea-8054-9270162ca6e0.gif)

Changed the way of approaching the exercise and the states that the main activity has. Now we had a JSON file where we take the information

2020-04-09 16:29 UTC, SartiMau requested changes

2020-04-09 16:29 UTC, SartiMau commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/DetailsCityActivity.kt
> +        Toast.makeText(this, cityName.toString(), Toast.LENGTH_SHORT).show()
this should happen through the ViewModel of this activity

2020-04-09 16:29 UTC, SartiMau commented on WheaterApp/app/src/main/java/com/example/weatherapp/viewmodels/CityMainViewModel.kt
> +    override fun createCityList(jsonArray: JSONArray) {
this must be in a UseCase

2020-04-09 16:29 UTC, SartiMau commented on WheaterApp/app/src/main/java/com/example/weatherapp/viewmodels/CityMainViewModel.kt
> +    fun getCityId(name: String): Int {
same, this must be in a UseCase

2020-04-09 16:53 UTC, mauroLonghi commented on WheaterApp/app/src/main/java/com/example/weatherapp/utils/Data.kt
> +    SUCCESSFUL,
OK, but if it is not useful in this PR, maybe not put now.

2020-04-09 17:00 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/utils/Data.kt
> +    SUCCESSFUL,
Done

2020-04-09 19:36 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/viewmodels/CityMainViewModel.kt
> +    fun getCityId(name: String): Int {
Done

2020-04-13 13:27 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/viewmodels/CityMainViewModel.kt
> +    override fun createCityList(jsonArray: JSONArray) {
Done

2020-04-13 13:28 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/DetailsCityActivity.kt
> +        Toast.makeText(this, cityName.toString(), Toast.LENGTH_SHORT).show()
removed because it's not necessary for this PR

2020-04-13 13:31 UTC, mauroLonghi approved these changes

2020-04-13 13:55 UTC, SartiMau requested changes

2020-04-13 13:55 UTC, SartiMau commented on WheaterApp/app/src/main/java/com/example/weatherapp/viewmodels/CityMainViewModel.kt
> +        val stringList = mutableListOf<String>()
maybe you can do all in the useCase.. including the for statement, and the usecase will return the stringList

so this method can be something like 

**return createCityListIdUseCase(listOfCity, jsonArray)**

2020-04-13 13:55 UTC, SartiMau commented on WheaterApp/data/src/main/java/com/example/data/repositories/CreateCityListUseCaseImpl.kt
> +package com.example.data.repositories
this implementation must be in domain. it not use nothing from data.

2020-04-13 13:55 UTC, SartiMau commented on WheaterApp/data/src/main/java/com/example/data/repositories/GetCityByIdUseCaseImpl.kt
> +package com.example.data.repositories
same here

2020-04-13 14:05 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/viewmodels/CityMainViewModel.kt
> +        val stringList = mutableListOf<String>()
Done!

2020-04-13 14:12 UTC, BQuinteros commented on WheaterApp/data/src/main/java/com/example/data/repositories/CreateCityListUseCaseImpl.kt
> +package com.example.data.repositories
Done!

2020-04-13 14:12 UTC, BQuinteros commented on WheaterApp/data/src/main/java/com/example/data/repositories/GetCityByIdUseCaseImpl.kt
> +package com.example.data.repositories
Done!

2020-04-13 15:28 UTC, SartiMau approved these changes

2020-04-13 16:14 UTC, mauroLonghi approved these changes

2020-04-13 16:17 UTC, lucianoeli approved these changes

2020-04-13 16:25 UTC, merged

2020-04-13 16:26 UTC, nicolbidone commented on WheaterApp/di/src/main/java/com/example/di/KoinModules.kt
> +    single<CreateCityListUseCase> { CreateCityListUseCaseImpl() }
Do you need to use a single to inject this?
https://proandroiddev.com/koin-in-feature-modules-project-6329f069f943