SplashScreen
BQuinteros/WeatherApp pull request #5
Opened 2020-04-14 16:05 UTC by BQuinteros

Added splash screen and the functionality to run in another thread the reading of JSON file. Adding the new screen I need to refactor some activities and changed his functionality
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/56684696/79247119-7a25c300-7e50-11ea-869d-e177b693a9f6.gif)

2020-04-14 16:51 UTC, lucianoeli commented on WheaterApp/app/src/main/java/com/example/weatherapp/viewmodels/SplashScreenViewModel.kt
> +    override val mutableMainState: MutableLiveData<Event<Data<City>>> = MutableLiveData()
this one should be private.

2020-04-14 16:58 UTC, SartiMau requested changes

2020-04-14 16:58 UTC, SartiMau commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +        val adapter = ArrayAdapter(this, android.R.layout.simple_list_item_1, listOfCities)
from where do you get the listOfCities variable?

2020-04-14 16:58 UTC, SartiMau commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/SplashScreenActivity.kt
> +    override fun nextActivity() {
this method is not necessary you can call the start activity from the updateUI method

2020-04-14 16:58 UTC, SartiMau commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/SplashScreenActivity.kt
> +        viewModel.createCityList(json)
same here, call this from readJSONFile method as this line is used only one time

2020-04-14 16:58 UTC, SartiMau commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/SplashScreenActivity.kt
> +        Toast.makeText(this, MESSAGE, Toast.LENGTH_SHORT).show()
same.. you call this only one time

2020-04-14 17:34 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/viewmodels/SplashScreenViewModel.kt
> +    override val mutableMainState: MutableLiveData<Event<Data<City>>> = MutableLiveData()
Done!

2020-04-14 17:36 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/SplashScreenActivity.kt
> +    override fun nextActivity() {
Done!

2020-04-14 17:38 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/SplashScreenActivity.kt
> +        Toast.makeText(this, MESSAGE, Toast.LENGTH_SHORT).show()
Done!

2020-04-14 17:38 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/SplashScreenActivity.kt
> +        viewModel.createCityList(json)
Done!

2020-04-14 17:47 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +        val adapter = ArrayAdapter(this, android.R.layout.simple_list_item_1, listOfCities)
I'm taking from CityViewModel

2020-04-14 18:25 UTC, BQuinteros commented
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/56684696/79259966-ecec6980-7e63-11ea-844d-6de1332130fe.gif)

2020-04-14 18:31 UTC, mauroLonghi approved these changes

2020-04-14 18:39 UTC, lucianoeli approved these changes

2020-04-14 18:49 UTC, SartiMau requested changes

2020-04-14 18:49 UTC, SartiMau commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +        val adapter = ArrayAdapter(this, android.R.layout.simple_list_item_1, listOfCities)
fix this based on the just talked

2020-04-15 13:26 UTC, mauroLonghi commented on WheaterApp/app/src/main/java/com/example/weatherapp/contracts/SplashScreenContract.kt
> +        val mainState: LiveData<Event<Data<City>>>
Why you define this variable in the interface?

2020-04-15 13:34 UTC, mauroLonghi commented on WheaterApp/domain/src/main/java/com/example/domain/usecases/GetJSONData.kt
> +interface GetJSONData {
Maybe you can group thats interfaces in only one file...not it wrong it a suggestion,

2020-04-15 13:55 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/contracts/SplashScreenContract.kt
> +        val mainState: LiveData<Event<Data<City>>>
Removed.

2020-04-15 14:03 UTC, BQuinteros commented on WheaterApp/domain/src/main/java/com/example/domain/usecases/GetJSONData.kt
> +interface GetJSONData {
Yes, I prefer to create one file with all the functionality inside

2020-04-15 14:16 UTC, mauroLonghi approved these changes

2020-04-15 15:22 UTC, nicolbidone approved these changes

2020-04-15 16:20 UTC, SartiMau requested changes

2020-04-15 16:20 UTC, SartiMau commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +        val adapter = ArrayAdapter(this, android.R.layout.simple_list_item_1, JSONDataUseCase.getJSONData())
the useCase should be called from the ViewModel not the activity

2020-04-15 16:34 UTC, BQuinteros commented on WheaterApp/app/src/main/java/com/example/weatherapp/activities/CityMainActivity.kt
> +        val adapter = ArrayAdapter(this, android.R.layout.simple_list_item_1, JSONDataUseCase.getJSONData())
Done

2020-04-15 16:37 UTC, SartiMau approved these changes

2020-04-15 17:22 UTC, lucianoeli approved these changes

2020-04-15 18:08 UTC, nicolbidone approved these changes

2020-04-15 18:11 UTC, mauroLonghi approved these changes

2020-04-15 18:18 UTC, merged